// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnSWborVtqdtkaEuJBe41a9oqZzwMtPKU',
    appId: '1:936939733023:web:e0a7e2381e08d95986d52a',
    messagingSenderId: '936939733023',
    projectId: 'dandando-2f861',
    authDomain: 'dandando-2f861.firebaseapp.com',
    storageBucket: 'dandando-2f861.firebasestorage.app',
    measurementId: 'G-QDHY6NQJ7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXips1fueZMp6hjlZ65MA7bcXHKyLnZ2s',
    appId: '1:936939733023:android:ff71e9379796045b86d52a',
    messagingSenderId: '936939733023',
    projectId: 'dandando-2f861',
    storageBucket: 'dandando-2f861.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHGmDhgik6JDf7LipEDunKPqn1A9c4g04',
    appId: '1:936939733023:ios:9597a42560d71aa286d52a',
    messagingSenderId: '936939733023',
    projectId: 'dandando-2f861',
    storageBucket: 'dandando-2f861.firebasestorage.app',
    iosBundleId: 'com.example.dandando',
  );
}
